version: '3'

services:
#  app:
#    container_name: ntopng
#    image: ntop/ntopng:stable
#    volumes:
#      - data:/var/lib/ntopng
#      - ./pcap:/pcap
#      - ./ntopng.conf:/ntopng.conf:ro
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      - TZ=Europe/Rome
#    command:
#      - "/ntopng.conf"
#    ports:
#        - 3000:3000
#    depends_on:
#      fritzpcap:
#        condition: service_healthy
services:
  webshark:
    image: qxip/webshark
    ports:
      - "8080:8085"
    volumes:
      - ./pcap:/captures
    networks:
      - proxy
    restart: unless-stopped

  fritzpcap:
    build: ./fritzpcap
    environment:
      - FRITZIP=http://192.168.178.1
      - FRITZUSER=fritz8565
      - FRITZPWD=
    volumes:
      - ./pcap:/pcap
    restart: unless-stopped

volumes:
  data:


networks:
  proxy:
